import { CodeFileType, SupportedLanguage, SupportedFramework } from '@/packages/types/src';
import { NamingEngine } from './naming-formatting-engine';

export interface CodeGenerationRequest {
  name: string;
  fileType: CodeFileType;
  framework: SupportedFramework;
  language: SupportedLanguage;
  description?: string;
  parameters?: Record<string, string>;
}

export class CodeGeneratorService {
  public generateCodeTemplatePattern(request: CodeGenerationRequest): string {
    const { name, fileType, framework, language } = request;
    const pascalName = NamingEngine.toPascalCase(name);
    const camelName = NamingEngine.toCamelCase(name);
    const kebabName = NamingEngine.toKebabCase(name);

    if (language === 'Python') {
      return this.generatePythonCode(name, fileType, framework);
    }
    if (language === 'Dart') {
      return this.generateDartCode(name, fileType);
    }

    // Default TypeScript / JavaScript Code Generation Patterns
    switch (fileType) {
      case 'Component':
        return `'use client';\n\nimport React from 'react';\n\ninterface ${pascalName}Props {\n  title?: string;\n  className?: string;\n  children?: React.ReactNode;\n}\n\nexport const ${pascalName}: React.FC<${pascalName}Props> = ({\n  title = '${pascalName}',\n  className = '',\n  children\n}) => {\n  return (\n    <div className={\`p-4 rounded-xl border border-zinc-800 bg-zinc-900/50 \${className}\`}>\n      <h3 className="text-sm font-semibold text-zinc-100">{title}</h3>\n      {children && <div className="mt-2 text-xs text-zinc-400">{children}</div>}\n    </div>\n  );\n};\n\nexport default ${pascalName};\n`;

      case 'Page':
        return `'use client';\n\nimport React from 'react';\n\nexport default function ${pascalName}Page() {\n  return (\n    <div className="min-h-screen p-8 bg-zinc-950 text-zinc-100 font-sans">\n      <header className="mb-6">\n        <h1 className="text-2xl font-bold tracking-tight">${pascalName}</h1>\n        <p className="text-xs text-zinc-400 mt-1">Generated by Enterprise AI CEO Coding Engine.</p>\n      </header>\n      <main className="grid grid-cols-1 md:grid-cols-2 gap-4">\n        <div className="p-6 bg-zinc-900 border border-zinc-800 rounded-xl">\n          <h2 className="text-sm font-medium text-zinc-200">Main Workspace View</h2>\n        </div>\n      </main>\n    </div>\n  );\n}\n`;

      case 'Hook':
        return `import { useState, useEffect, useCallback } from 'react';\n\nexport interface ${pascalName}State {\n  data: unknown;\n  loading: boolean;\n  error: Error | null;\n}\n\nexport function ${camelName.startsWith('use') ? camelName : `use${pascalName}`}() {\n  const [state, setState] = useState<${pascalName}State>({\n    data: null,\n    loading: true,\n    error: null\n  });\n\n  const refetch = useCallback(() => {\n    setState(prev => ({ ...prev, loading: true }));\n    setTimeout(() => {\n      setState({ data: { status: 'success' }, loading: false, error: null });\n    }, 500);\n  }, []);\n\n  useEffect(() => {\n    refetch();\n  }, [refetch]);\n\n  return { ...state, refetch };\n}\n`;

      case 'API':
        return `import { NextRequest, NextResponse } from 'next/server';\n\nexport async function GET(req: NextRequest) {\n  return NextResponse.json({\n    status: 'ok',\n    endpoint: '${kebabName}',\n    timestamp: new Date().toISOString()\n  });\n}\n\nexport async function POST(req: NextRequest) {\n  const body = await req.json();\n  return NextResponse.json({\n    status: 'created',\n    received: body\n  }, { status: 201 });\n}\n`;

      case 'Service':
        return `export interface ${pascalName}Config {\n  endpoint?: string;\n  timeoutMs?: number;\n}\n\nexport class ${pascalName}Service {\n  private endpoint: string;\n\n  constructor(config?: ${pascalName}Config) {\n    this.endpoint = config?.endpoint || '/api/${kebabName}';\n  }\n\n  public async execute(payload: Record<string, unknown>): Promise<{ success: boolean; data: unknown }> {\n    return {\n      success: true,\n      data: { payload, processedAt: new Date().toISOString() }\n    };\n  }\n}\n\nexport const ${camelName}Service = new ${pascalName}Service();\n`;

      case 'Types':
        return `export interface ${pascalName}Model {\n  id: string;\n  name: string;\n  status: 'active' | 'inactive' | 'pending';\n  createdAt: string;\n}\n\nexport type ${pascalName}Action = 'CREATE' | 'UPDATE' | 'DELETE';\n`;

      case 'Utility':
        return `export function ${camelName}(input: string): string {\n  if (!input) return '';\n  return input.trim().toLowerCase();\n}\n`;

      case 'Config':
        return `export const ${camelName}Config = {\n  env: process.env.NODE_ENV || 'development',\n  apiPrefix: '/api/v1',\n  version: '1.0.0'\n};\n`;

      case 'Middleware':
        return `import { NextRequest, NextResponse } from 'next/server';\n\nexport function middleware(req: NextRequest) {\n  const token = req.headers.get('authorization');\n  if (!token && req.nextUrl.pathname.startsWith('/api/protected')) {\n    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });\n  }\n  return NextResponse.next();\n}\n`;

      case 'Layout':
        return `'use client';\n\nimport React from 'react';\n\nexport default function ${pascalName}Layout({ children }: { children: React.ReactNode }) {\n  return (\n    <div className="w-full min-h-screen bg-zinc-950 text-zinc-100 flex flex-col">\n      <div className="flex-1">{children}</div>\n    </div>\n  );\n}\n`;

      case 'Provider':
        return `'use client';\n\nimport React, { createContext, useContext, useState } from 'react';\n\ninterface ${pascalName}ContextType {\n  value: string;\n  setValue: (val: string) => void;\n}\n\nconst ${pascalName}Context = createContext<${pascalName}ContextType | undefined>(undefined);\n\nexport const ${pascalName}Provider: React.FC<{ children: React.ReactNode }> = ({ children }) => {\n  const [value, setValue] = useState('default');\n  return (\n    <${pascalName}Context.Provider value={{ value, setValue }}>\n      {children}\n    </${pascalName}Context.Provider>\n  );\n};\n\nexport function use${pascalName}() {\n  const context = useContext(${pascalName}Context);\n  if (!context) throw new Error('use${pascalName} must be used within ${pascalName}Provider');\n  return context;\n}\n`;

      default:
        return `// Enterprise Generated Code\nexport const ${camelName} = true;\n`;
    }
  }

  private generatePythonCode(name: string, fileType: CodeFileType, framework: SupportedFramework): string {
    const snakeName = NamingEngine.toSnakeCase(name);
    const pascalName = NamingEngine.toPascalCase(name);

    if (fileType === 'API' || framework === 'FastAPI') {
      return `from fastapi import APIRouter, HTTPException\nfrom pydantic import BaseModel\n\nrouter = APIRouter(prefix="/${snakeName}", tags=["${pascalName}"])\n\nclass ${pascalName}Item(BaseModel):\n    name: str\n    description: str | None = None\n\n@router.get("/")\nasync def get_${snakeName}():\n    return {"status": "ok", "service": "${pascalName}"}\n`;
    }

    return `class ${pascalName}:\n    """Enterprise Python Service Model"""\n    def __init__(self, name: str = "${snakeName}"):\n        self.name = name\n\n    def execute(self) -> dict:\n        return {"status": "success", "name": self.name}\n`;
  }

  private generateDartCode(name: string, fileType: CodeFileType): string {
    const pascalName = NamingEngine.toPascalCase(name);
    return `import 'package:flutter/material.dart';\n\nclass ${pascalName}Widget extends StatelessWidget {\n  const ${pascalName}Widget({super.key});\n\n  @override\n  Widget build(BuildContext context) {\n    return Container(\n      padding: const EdgeInsets.all(16.0),\n      child: Text('${pascalName} Enterprise Widget'),\n    );\n  }\n}\n`;
  }
}

export const codeGeneratorService = new CodeGeneratorService();
