import { SupportedLanguage, CodeFileType } from '@/packages/types/src';
import { LanguageManager } from './language-framework-manager';

export class NamingEngine {
  public static toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }

  public static toCamelCase(str: string): string {
    const pascal = this.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }

  public static toKebabCase(str: string): string {
    return str
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .replace(/[^a-zA-Z0-9]/g, '-')
      .toLowerCase()
      .replace(/-+/g, '-');
  }

  public static toSnakeCase(str: string): string {
    return str
      .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .toLowerCase()
      .replace(/_+/g, '_');
  }

  public static generateStandardFileName(
    name: string,
    fileType: CodeFileType,
    language: SupportedLanguage
  ): { fileName: string; extension: string } {
    const meta = LanguageManager.getMeta(language);
    let extension = meta.extension;

    if ((language === 'TypeScript' || language === 'JavaScript') && (fileType === 'Component' || fileType === 'Page' || fileType === 'Layout')) {
      extension = language === 'TypeScript' ? '.tsx' : '.jsx';
    }

    let cleanName = name;
    if (language === 'TypeScript' || language === 'JavaScript') {
      if (fileType === 'Component' || fileType === 'Page' || fileType === 'Layout' || fileType === 'Provider') {
        cleanName = this.toPascalCase(name);
      } else if (fileType === 'Hook') {
        cleanName = name.startsWith('use') ? this.toCamelCase(name) : `use${this.toPascalCase(name)}`;
      } else {
        cleanName = this.toKebabCase(name);
      }
    } else if (language === 'Python') {
      cleanName = this.toSnakeCase(name);
    } else if (language === 'Dart') {
      cleanName = this.toSnakeCase(name);
    } else {
      cleanName = this.toPascalCase(name);
    }

    return {
      fileName: `${cleanName}${extension}`,
      extension
    };
  }
}

export class FormattingEngine {
  public static formatCode(content: string, language: SupportedLanguage): string {
    if (!content) return '';
    
    const trimmed = content.trim();
    const lines = trimmed.split('\n');

    // Remove redundant blank lines (more than 2 consecutive blank lines)
    const normalizedLines: string[] = [];
    let blankCount = 0;

    for (const line of lines) {
      if (line.trim() === '') {
        blankCount++;
        if (blankCount <= 2) {
          normalizedLines.push('');
        }
      } else {
        blankCount = 0;
        normalizedLines.push(line);
      }
    }

    let formatted = normalizedLines.join('\n');
    if (!formatted.endsWith('\n')) {
      formatted += '\n';
    }

    return formatted;
  }

  public static generateHeaderComment(
    fileName: string,
    fileType: CodeFileType,
    language: SupportedLanguage
  ): string {
    const meta = LanguageManager.getMeta(language);
    const date = new Date().toISOString().split('T')[0];

    if (meta.commentSingle === '#') {
      return `# ============================================\n# File: ${fileName}\n# Type: ${fileType}\n# Generated by Enterprise AI CEO Coding Engine (${date})\n# ============================================\n\n`;
    }

    return `/**\n * Enterprise AI CEO Coding Engine\n * File: ${fileName}\n * Type: ${fileType}\n * Date: ${date}\n */\n\n`;
  }
}
